apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: tds-group-3
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  ADMIN_JWT_SECRET: "${ADMIN_JWT_SECRET}"
  INTERNAL_SECRET: "${INTERNAL_SECRET}"
  REDIS_URL: "${REDIS_URL}"
  LOKI_URL: "${LOKI_URL}"
  LOKI_USER: "${LOKI_USER}"
  LOKI_TOKEN: "${LOKI_TOKEN}"
