apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: tds-group-3
type: Opaque
stringData:
  JWT_SECRET: "${JWT_SECRET}"
  ADMIN_JWT_SECRET: "${ADMIN_JWT_SECRET}"
  REDIS_URL: "${REDIS_URL}"
  INTERNAL_SECRET: "${INTERNAL_SECRET}"
